### ISSUE TITLE
App Redesign v2.0

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#598]
- [x] **🛑 SVG of the bags & background objects are required first**

The app's has a proper design now 🎉, use tailwind to restyle the app

<img alt="app screenshot bags page" src="https://play-lh.googleusercontent.com/NavC7yogkA1y73QktIVv0cNUVr4Kd2L0LMfv3L8femya_3IYzbR_deIHi_ljrPpNKatR=w2560-h1440-rw" height="400">

See the play store's screenshots for all page designs: https://play.google.com/store/apps/details?id=org.clothingloop.app

For overriding the ionic styles, in the `app/src/tailwind.css` file add

```css
ion-button {
  /* add css from tailwind classes to another class */
  @apply .tw-text-center .tw-mb-4;

  /* See custom properties in the ionic docs
  https://ionicframework.com/docs/api/button#css-custom-properties */
  --background: #93e9be;
  --background-hover: #9ce0be;
  --background-focused: #88f4be;

  --color: blue;

  --padding-top: 10px;
  --padding-bottom: 10px;
}

```
